#! /bin/sh

CONT=0
INC=1

../src/server 127.0.0.1 1234 ../config/config_file.txt > /dev/null &
../src/server 127.0.0.1 5678 ../config/config_file.txt > /dev/null &
sleep 1

echo "" > log_c1
echo "" > log_c2

for t in 1 2 3
do
./client1 ../config/config_file.txt >> log_c1 &
./client2 ../config/config_file.txt >> log_c2 &
sleep 1
if cmp log_c1 log_c2 > /dev/null
then CONT=$(($CONT+$INC))
fi
done

echo ""

if [ $CONT -eq 3 ]
then echo "OK"
else echo "FAIL"
fi

echo ""

killall server









